### ISSUE TITLE
팀프로젝트 주제(벌점) CRUD 기능 함수 정리

### ISSUE THREAD

**Issue by wonjunseol** [wonjunseol/OSS_TeamProject#1]
혹시 CRUD 기능중에 디테일하게 추가하고 싶으신 거 있으신가요?

벌점 수정하는 함수를 구현할 때  벌점 받은 이유에 대한 걸 수정하는 것을 생각해봤는데 어떠신가요?

**Comment by Hakyoungan** [comment]
좋은 것 같아요! 벌점 수위도 함께 수정할 수 있도록 하는건 어떨까요?

**Comment by wonjunseol** [comment]
좋습니다! 그러면 벌점 수정하는 함수에서는 벌점 받은 이유와 벌점 수위(각 이유에 대해 받는 벌점(ex. 무단 외박 1점, 외부인 출입 3점))에 대해 수정하는 함수를 만들면 될 것 같아요!

**Comment by Hakyoungan** [comment]
저희 생각해보니 수위는 딱히 없어도 될 것 같아요! 수위 보다는 몇점을 추가할 지 정해서 추가시키는 건 어떠신가요? 사례나 수위 없이 하나의 총벌점으로 더하고 빼는 형식으로 변경하는건 어떠신가요?

**Comment by wonjunseol** [comment]
네네 그러면 총벌점을 몇점 추가하고 몇점 삭제하고 수정하는 걸로 변경하면 될 것 같아요!
