### ISSUE TITLE
구조체 리스트

### ISSUE THREAD

**Issue by Hakyoungan** [wonjunseol/OSS_TeamProject#2]
저희 구조체 리스트 구체화해야 하는데
-이름
-벌점
-사례
외에 어떤걸 추가하면 좋은가요?

**Comment by wonjunseol** [comment]
좋습니다! 
각 학생의 벌점 리스트를 볼 때 총 벌점을 몇 점 받았는지도 추가를 해주면 좋을 것 같아요! 
그래서 리스트에 총 벌점을 추가하는 건 어떠신가요?!

**Comment by Hakyoungan** [comment]
좋아요! 추가로 생각 나시는거 있으면 이곳에 계속 적어봐요!

**Comment by Hakyoungan** [comment]
저희 <구조체> 리스트는 
이름
학번
벌점[20]
사례[20]
총 벌점
팀 교수님
기숙사이름
호실 
로 확정 지을까요?

**Comment by wonjunseol** [comment]
네 좋습니다!

**Comment by Hakyoungan** [comment]
저희 구조체 리스트는 구조체 변수 구체화 이슈에서 정리해 놓은 걸로 확정 했으므로 이 이슈는 닫도록 할께요!
