### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by wonjunseol** [wonjunseol/OSS_TeamProject#3]
저희 총 만들 메뉴가 10개인데 5개씩 나눠서 개발하면 어떨까요?

**Comment by Hakyoungan** [comment]
제가 메뉴 홀수번 코드 작성하는 걸로 할께요 !

**Comment by wonjunseol** [comment]
넵넵! 그러면 제가 짝수번 개발하도록 하겠습니다!

**Comment by wonjunseol** [comment]
둘이 약간 헷갈린 것 같은데 제가 홀수번 개발하겠습니다!
즉
벌점 추가 기능
벌점 수정 기능
벌점 검색 기능
파일 저장 기능
공지사항 및 벌점 리스트 보기 기능
구현하겠습니다!

**Comment by Hakyoungan** [comment]
아네네! 제가 짝수번+파일로드 구현하는 걸로 할께요!
