### ISSUE TITLE
프로젝트 메뉴에 대한 구체화

### ISSUE THREAD

**Issue by wonjunseol** [wonjunseol/OSS_TeamProject#4]
1. 벌점 추가(학번으로 검색해서 찾고 벌점과 사례 추가)
2. 벌점 삭제(리스트별로 삭제)
3. 벌점 수정(사례와 벌점 수위 수정)
4. 벌점 리스트함수(리스트, 총 벌점, 마지막 벌점 받은 날로부터 계산해서 문구 출력(ex. 7점시 교수님 면담. 10점시 퇴거))
5. 벌점 검색(예를 들어 벌점 7점인 학생 리스트를 조회)
6. 사례 검색 후 받은 학생들이 이 사례로 몇점 받았는지 검색
7. 파일 저장
8. 전체 삭제(새 학기마다 refresh하기위해 삭제)
9. 공지사항 및 벌점 리스트
10. 종료

저번에 나눈 얘기입니다!
이 메뉴들 가지고 역할 분담 하면 될 것 같아요!

**Comment by Hakyoungan** [comment]
네 그럼 저희 저번에 얘기 나눈대로 짝수 홀수 각자 맡아서 하는 걸로 하고 여기에 학번으로 학생 검색하는 함수 하나 추가해서 제가 더 만들도록 하겠습니다. !

**Comment by wonjunseol** [comment]
저희 그러면 학생 삭제하는 함수 넣는 거 어떨까요? 예를 들어 중도 휴학을 하거나 자퇴를 하는 학생들이 있을 때 전체 삭제를 하는 경우밖에 없어서 시스템을 관리하는데 불편할 것 같다는 생각이 들어서요!

**Comment by Hakyoungan** [comment]
1. 벌점 추가
2. 벌점 삭제(학번으로 학생 검색 후 벌점 삭제)
3. 학생 삭제(학번으로 학생 검색 후 학생 삭제)
4. 벌점 수정
5. 벌점을 받은 학생 조회
6. 학번 검색
7. 벌점 검색(총 벌점이 찾는 벌점에 해당하는 학생들 리스트)
8. 상담 신청
9. 파일 저장
10. 전체삭제
11. 공지사항 및 벌점 종류
0. 종료
최종적으로 이렇게 하는 걸로 하겠습니다!
