### ISSUE TITLE
구조체 변수 구체화

### ISSUE THREAD

**Issue by Hakyoungan** [wonjunseol/OSS_TeamProject#5]
<구조체>
이름 name
학번 studentId
벌점[20] penaltyNum
사례 (reason? )
총 벌점 totalNum
팀 교수님 teamProf
기숙사이름 rcName
호실 roomNum
 
변수 이름 정해야할 것 같습니다. 제가 생각한 것들 옆에 넣어놓겠습니다. 더 괜찮은 변수 이름이나 아이디어 있으시면 알려주세요!

**Comment by Hakyoungan** [comment]
이름 char name[30]
학번 int studentId
벌점[20] int penaltyNum[20]
사례 (reason? )string 변수이름[20]
총 벌점 char totalNum
팀 교수님 char teamProf[30]
기숙사이름 char rcName[30]
호실 int roomNum
이것도 확인해주세요!

**Comment by wonjunseol** [comment]
사례도 char로 하면 될 것 같아요!
이름 -> char name[30]
학번 -> int studentId
벌점[20] -> int penaltyNum[20]
사례 (reason? )-> char reason[20]
총 벌점 -> char totalNum
팀 교수님 -> char teamProf[30]
기숙사이름 -> char rcName[30]
호실 -> int roomNum

이렇게 변수 이름 정하고 개발하면 될 것 같아요!

**Comment by wonjunseol** [comment]
사례도 char로 하면 될 것 같아요!
이름 -> char name[30]
학번 -> int studentId
벌점[20] -> int penaltyNum[20]
사례 (reason? )-> char reason[20]
총 벌점 -> char totalNum
팀 교수님 -> char teamProf[30]
기숙사이름 -> char rcName[30]
호실 -> int roomNum

이렇게 변수 이름 정하고 개발하면 될 것 같아요!

**Comment by Hakyoungan** [comment]
네! 저희 사례 추가할때 사례가 하나 이상의 단어일 수도 있으니까 char reason[20][30]으로 해요! 그래서 벌점이 추가될 때마다 첫번째 배열이 늘어난다고 치고 구조체 안에 int indexNum 을 넣는건 어떨까요. 그래야지 만약 안하경 학생을 찾아서 벌점을 추가한다고 했을때 indexNum일 있어야지 penaltyNum[indexNum++], char reason[indexNum++] 이렇게 사용할 수 있을거 같아요.

**Comment by wonjunseol** [comment]
오 좋습니다! 저는 그때그때마다 넣을 생각이었는데 변수 하나를 넣어서 그 값은 계속 유지해놓는 게 나을 것 같아요! 그러면 덜 복잡하고 값도 바로바로 알 수 있어서 좋을 것 같네요! 그렇게 하는 게 좋을 것 같아요!

**Comment by Hakyoungan** [comment]
저희 penaltynum 과 totalnum은 데이터값이 작으니까 unsigned char로 쓰는게 좋을거 같습니다!

**Comment by wonjunseol** [comment]
넵넵! 그리고 구조체 이름은 student로 통일하고 배열의 이름은 plist[100] 이걸로 잡는 게 좋을 것 같아요!

**Comment by Hakyoungan** [comment]
typedef struct {
    char name[30];
    int studentId;
    unsigned char penaltyNum[20];
    char reason[20];
    unsigned char totalNum;
    int indexNum;
    char teamProf[30];
    char rcName[30];
    int roomNum;
}student;

int main() {
    student plist[100];
}

**Comment by Hakyoungan** [comment]
저희 저번 팀플 결과 기능 바뀌면서 변경된 구조체 올리겠습니다!
typedef struct {
char name[30];
int studentId;
int totalNum;
char teamProf[30];
char rcName[30];
int roomNum;
char apply; //Y/N
}student;

int main() {
student plist[100];
}
이렇게 하는걸로 할께요! 한번 확인해 주시고 변경해야할 것 있으면 말해주세요!
