### ISSUE TITLE
삭제기능 및 continue 조건

### ISSUE THREAD

**Issue by Hakyoungan** [wonjunseol/OSS_TeamProject#6]
제가 삭제 할 때 학생의 totalNum을 0으로 변경하도록 하겠습니다! 그래서 학생 배열로 for 문 돌리시에는 totalNum==0 인 경우 continue 하는 조건으로 코드 짜시면 될 거 같아요!

**Comment by wonjunseol** [comment]
좋은 것 같아요~! 저도 그렇게 구현하도록 하겠습니다!

**Comment by wonjunseol** [comment]
그 저희 나중에 학번 검색할 때 오류가 생길 수 있어서 studentId도 0으로 통일시키도록 하겠습니다!

**Comment by Hakyoungan** [comment]
좋아요 :)
