### ISSUE TITLE
삭제 및 수정 할 학생 검색 방법

### ISSUE THREAD

**Issue by Hakyoungan** [wonjunseol/OSS_TeamProject#7]
저희 학생 삭제 및 수정할 때 리스트 번호로 찾는걸로 할까요 아니면 학번으로 찾는걸로 할까요?? 만약 데이터가 많아졌을 경우에는 리스트 번호로 찾는게 어렵지 않을까 생각하는데, 의견이 어떠신지 말씀해주세요!

**Comment by wonjunseol** [comment]
네네! 괜찮은 것 같아요! 원래 이름으로 찾는 것을 생각했는데 생각해보니 동명이인이 있을 수도 있으니 학번으로 하는 게 나을 것 같습니다!

**Comment by Hakyoungan** [comment]
네 그럼 그렇게 하는걸로 하겠습니다!
